### ISSUE TITLE
Invalid URL error while installation

### ISSUE THREAD

**Issue by Harshiv-Patel** [Hax4us/java#2]
The installation script does not complete successfully, it says in output:

`\033[32m[*] Now wait until jdk-8 is installing ...🕛🕧\033[0m

wget: not an http or ftp url: https://github.com/Hax4us/java/releases/download/v8-151/jdk8_arm.tar.gz

\033[32m[*] Moving jdk into system ...\033[0m
mv: cannot stat 'jdk8_arm.tar.gz': No such file or directory     
\033[32m[*] Extracting ...\033[0m
tar: can't open 'jdk8_arm.tar.gz': No such file or directory

\033[32m[*] Moving wrapper scripts for java 8\033[0m
mv: cannot stat 'bin/*': No such file or directory

\033[34mHappy java :D\033[0m`

Should there be `echo -e` for escape sequences or something?

**Comment by Harshiv-Patel** [comment]
Also it says "killed" after I manually installed your binaries. Glib method does not seem to work with armv7 devices, running Android Lollipop 5.1.1

**Comment by Hax4us** [comment]
@Harshiv-Patel thnx for info.. i will look into this ..actually i hve no any armv7 device now i will test

**Comment by Hax4us** [comment]
-e i forget lol

**Comment by Harshiv-Patel** [comment]
Please be careful in these scripts, you might accidentally screw up other things...

**Comment by Harshiv-Patel** [comment]
waiting for armv7 binaries eagerly here..

**Comment by aiisuika** [comment]
@Harshiv-Patel busybox's `wget` doesn't have ssl support, run ```bash
pkg in wget
hash -r
```
and volia!

**Comment by Harshiv-Patel** [comment]
Unfortunately the output of "java" after installation is single word "killed" without any error code or anything. Installing "wget" actually solved the original issue. The java binaries however, would not run, Should I close this issue and reopen other for binaries being "killed" ?

**Comment by aiisuika** [comment]
If it says killed, thats android that killed it. Java is quite a resource hungry program, your device may not have enough ram+swap, so the OOM killer came after it.

**Comment by Harshiv-Patel** [comment]
Qcom snapdragon 410 processor, 2GB device RAM, running Android Lollipop 5.1.1. Termux has been pushed to memory card by "Apps2SD" app as it takes large amount of space(This hasn't affected working of Termux AFAIK).
I think the "killed" message has something to do with my kernel being in "enforcing" mode.
I've made a pull request for missing "-e" switch in "configurejava.sh" script. So I'll close this issue when it is merged.

**Comment by aiisuika** [comment]
My device runs java fine with selinux in enforing mode, so that can't be the case.

**Comment by Harshiv-Patel** [comment]
what device are you using for testing @aiisuika ?
Also closing this issue as pull request is merged.

**Comment by aiisuika** [comment]
Exynos 7885 Octa (2x2.2 GHz Cortex-A73 & 6x1.6 GHz Cortex-A53) 4GB RAM, Android Nougat 7.1.1
Termux is in internal storage.

**Comment by Harshiv-Patel** [comment]
so it's on, arm v8. I'll have to check it on any other armv8 devices. perhaps it doesn't work on arm v7 devices.

**Comment by aiisuika** [comment]
The pr is broken, `ee` isn't expanded on lines with `ee" ...`. lol

**Comment by Harshiv-Patel** [comment]
strange. `shopt -s expand_aliases` is supposed to enable alias expansion. The "echo" without the "-e" switch is not supposed to process escape sequences, or is it inverse of it in arm v8 binaries?

**Comment by aiisuika** [comment]
`ee" ...` parses as `ee<space>...`

**Comment by Harshiv-Patel** [comment]
Thank you for pointing it out. A new PR I suppose.
